### ISSUE TITLE
平賀正樹_今日の進捗(9/4)

### ISSUE THREAD

**Issue by ichiyajou0125** [conea0/python-basic-course#19]
1_004を作り終えた

**Comment by teke4869** [comment]
一つ問題を作り終えて、何か困ったことなどありませんか？
今日の作業時間も教えてくださいm(_ _"m)

**Comment by ichiyajou0125** [comment]
作業時間：3時間
資料制作はそこまで難しくなかったが、練習問題の出題傾向などで少し戸惑った

**Comment by teke4869** [comment]
お疲れさまでした。
練習問題を考えるのはとても難しいとおもいますが、そんなに悩みこまず、東大の問題を参考にしたり、僕に聞いてもらってもいいので頑張っていきましょう！
明日もお願いします！
