### ISSUE TITLE
菅原彩華_今日の進捗(9/4)

### ISSUE THREAD

**Issue by ayaka26** [conea0/python-basic-course#21]
1_003と1_006の説明資料をあらかた作った。
作業時間は1時間くらい？(今からまだ作業する予定です、練習問題作ります)
とりあえず今はまだ困ったことないので、困り次第随時聞きます。

**Comment by teke4869** [comment]
お疲れさまでした。
困ったことがなくてよかったです。
問題作成は作業要素高めですが、小学生や中学生に問題を投げかけるような感じでお願いします！
