### ISSUE TITLE
平賀正樹_進捗報告

### ISSUE THREAD

**Issue by ichiyajou0125** [conea0/python-basic-course#35]
作業時間：4時間

作業内容：1_005を概ね終わらせた。
　　　　　2_004を途中まで終わらせた。

練習問題の参考を見てみても、量が少なく、ちょうどいい難易度がわからず苦戦した。

質問：Issuesに毎日新しく書いていくと、見づらくなっていくと思うのですが、ここの下にメンションして書いていく、などしなくても大丈夫ですか？

**Comment by syuya2036** [comment]
@ichiyajou0125 
日報は自分が取り組んでいる最中のissueにコメントとして書く、という指示だったはずです！

**Comment by ichiyajou0125** [comment]
誤解していました！明日からはそのようにします！！お騒がせしました！

**Comment by syuya2036** [comment]
クローズしておきますね😄
