### ISSUE TITLE
ローカルでcommitできない問題

### ISSUE THREAD

**Issue by syuya2036** [conea0/python-basic-course#36]
@ayaka26 
コミットできない問題を解決するためのissueを作ってみました。
インターン中なので、業務の合間を縫っての返信になること、ご承知ください。
とりあえずコミット時のエラーメッセージをここに貼ってください

**Comment by teke4869** [comment]
@ayaka26 
 それからどうなった？
 今の状況聞きたい

**Comment by ayaka26** [comment]
彩華です。
返信遅れてごめん。進捗というか状況は、解決してなくて、あべりょうに見せた時と変わってない。

しゅうやくんへ
エラーが起きるというか、去年のweb作成のときに起こったvscodeでコミットが終わらない(始まらないのかな？)現象が起きてます。去年どうにか解決した記憶があるんだけどその時どうやったか覚えてたら教えて欲しい。

今日、インターンの準備と私情で家帰るの19時とかになりそう。夜は作業する予定です。

**Comment by syuya2036** [comment]
@ayaka26 
コミットメッセージ書いてますか？

**Comment by ayaka26** [comment]
始めは書かないでコミットして、数分経っても終わらなかった感じです。コメント書くと変わりますか？

**Comment by syuya2036** [comment]
@ayaka26 

書いてやってみてください。

**Comment by ayaka26** [comment]
了解です。

**Comment by ayaka26** [comment]
ごめん、さっき聞き忘れたんだけど、他の006とかもプルリクエストのやり方は一緒でいいの？

**Comment by teke4869** [comment]
できた￥
